CREATE TABLE items(
	 id int NOT NULL GENERATED BY DEFAULT AS IDENTITY(START WITH 1),
	 price int,
	 name varchar(75),
	 category varchar(75)
);
insert into items (name, price, category) values ('HDD 500GB', 240, 'HDD');
insert into items (name, price, category) values ('HDD 750GB', 300, 'HDD');
insert into items (name, price, category) values ('HDD 1000GB', 340, 'HDD');
insert into items (name, price, category) values ('SDD 128GB', 270, 'HDD');
insert into items (name, price, category) values ('RAM 2GB', 45, 'RAM');
insert into items (name, price, category) values ('RAM 4GB', 140, 'RAM');
insert into items (name, price, category) values ('RAM 8GB', 190, 'RAM');
insert into items (name, price, category) values ('RAM 16GB', 240, 'RAM');
insert into items (name, price, category) values ('SDD 256GB', 540, 'HDD');
insert into items (name, price, category) values ('RAM 1GB', 30, 'RAM');
